name: storybook

packages:
  - "packages/**"

command:
  version:
    workspaceChangelog: false

scripts:
  format: dart format --set-exit-if-changed .
  pub_get:
    exec: flutter pub get
  analyze: flutter analyze .

  test:
    run: flutter test --no-pub
    exec:
      concurrency: 1
    packageFilters:
      dirExists:
        - test

  check_master:
    run: |
      melos run format \
        && melos run pub_get \
        && melos run analyze \
        && melos run test --no-select

  build:docs:
    exec: sh MELOS_ROOT_PATH/tool/build_docs.sh
    packageFilters:
      scope: storybook_flutter
