name: storybook_flutter
description: A storybook for Flutter widgets. Live preview of isolated widgets for faster development and showcase.
version: 0.1.5
homepage: https://github.com/ookami-kb/storybook_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ">=4.0.0 <5.0.0"
  recase: ">=2.0.1 <4.0.0"
  rxdart: ">=0.24.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
