name: storybook_flutter_example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  storybook_flutter:
    path: ..
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mews_pedantic: ^0.23.0

flutter:
  uses-material-design: true
